### ISSUE TITLE
使用openssl @ 2f33265 构建ohos-aarch64报错

### ISSUE THREAD

**Issue by OrreroVV** [ohos-rs/ohos-openssl#8]
![image](https://github.com/user-attachments/assets/af41789c-fb24-4a70-9abb-837122c1351d)

这是native版本：
![image](https://github.com/user-attachments/assets/4838305b-21b5-48a0-91d5-e48c6dc963a1)
其他两个架构构建正常，只有arm64的报错
这是为啥，大佬

**Comment by richerfu** [comment]
看起来可能是有些配置不对，导致中间产生的文件是格式不对的，辛苦提供下复现流程。 @OrreroVV

**Comment by OrreroVV** [comment]
> 看起来可能是有些配置不对，导致中间产生的文件是格式不对的，辛苦提供下复现流程。 @OrreroVV
系统版本：
![image](https://github.com/user-attachments/assets/66bf80ed-ae48-4c12-b05b-dfa6dc90c032)

下载的是native版本是：https://cidownload.openharmony.cn/version/Master_Version/OpenHarmony_5.0.2.43/20240924_020228/version-Master_Version-OpenHarmony_5.0.2.43-20240924_020228-ohos-sdk-public.tar.gz
![image](https://github.com/user-attachments/assets/7c3711eb-429f-4082-b420-ba1b7e65cfd1)

openssl选择的是2f33265
![image](https://github.com/user-attachments/assets/cc0728d1-d808-49af-ab9a-4535f9679a27)

在build.sh里面第一行添加了这个

![image](https://github.com/user-attachments/assets/4258ac79-769c-44d2-adf2-de7974e98943)

其余没有修改
执行命令
bash script/build.sh

出现如下：
![image](https://github.com/user-attachments/assets/8215ebd1-79ba-423d-b9a6-df6b82f07702)

**Comment by OrreroVV** [comment]
> 看起来可能是有些配置不对，导致中间产生的文件是格式不对的，辛苦提供下复现流程。 @OrreroVV

没事了大佬，我用的是release的代码跑的，clone的代码跑的没问题
